[package]
name = "karat_v2"
version = "0.0.1"
cairo-version = ">=2.10.1"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "./migrate"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }

[dev-dependencies]
cairo_test = ">=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.5.0" }

[[target.starknet-contract]]
sierra = true
build-external-contracts = [
  "dojo::world::world_contract::world",
]

# debug contract size issues
# needed by `sozo build --stats.by-tag`
# casm = true


#--------------------------
# Dojo profiles declaration
#
[profile.dev]
[profile.sepolia]
[profile.mainnet]
